import "server-only";
import type { Tx } from "./db";

/**
 * Audit trail writer. Called inside the same transaction as the change it
 * records. Metadata holds field NAMES and non-sensitive context only — never
 * raw personal values (phone, email, document text, descriptions).
 */
export type AuditAction =
  | "profile_created"
  | "profile_updated"
  | "profile_verified"
  | "onboarding_updated"
  | "onboarding_completed"
  | "education_created"
  | "education_updated"
  | "experience_created"
  | "experience_updated"
  | "achievement_created"
  | "achievement_updated"
  | "skill_created"
  | "skill_updated"
  | "project_created"
  | "project_updated"
  | "certification_created"
  | "certification_updated"
  | "portfolio_created"
  | "portfolio_updated"
  | "language_created"
  | "language_updated"
  | "authorization_created"
  | "authorization_updated"
  | "fact_verified"
  | "fact_deleted"
  | "fact_restored"
  | "preference_updated"
  | "target_locations_updated"
  | "document_uploaded"
  | "document_processed"
  | "document_processing_failed"
  | "document_deleted"
  | "document_downloaded"
  | "fact_created"
  | "fact_approved"
  | "fact_edited"
  | "fact_rejected"
  | "data_exported"
  | "sources_initialized"
  | "source_updated"
  | "source_enabled"
  | "source_disabled"
  | "source_auto_paused"
  | "job_created"
  | "job_updated"
  | "job_deleted"
  | "match_requested"
  | "match_completed"
  | "match_failed"
  | "match_invalidated"
  | "match_version_changed"
  | "match_recalculated"
  | "match_batch_started"
  | "match_batch_finished"
  | "match_batch_cancelled"
  | "matching_preferences_updated"
  | "research_started"
  | "research_completed"
  | "research_failed"
  | "research_refreshed"
  | "research_invalidated"
  | "source_added"
  | "claim_created"
  | "claim_rejected"
  | "claim_conflict"
  | "manual_note_added"
  | "manual_note_deleted"
  | "research_settings_updated"
  | "company_target_updated"
  | "search_profile_created"
  | "search_profile_updated"
  | "search_profile_duplicated"
  | "search_profile_enabled"
  | "search_profile_disabled"
  | "search_profile_deleted"
  | "search_config_updated"
  | "discovery_started"
  | "discovery_finished"
  | "source_tested"
  | "job_bookmarked"
  | "job_unbookmarked"
  | "job_hidden"
  | "job_restored"
  | "saved_search_created"
  | "saved_search_updated"
  | "saved_search_duplicated"
  | "saved_search_deleted"
  | "resume_created"
  | "resume_edited"
  | "resume_version_created"
  | "resume_restored"
  | "resume_duplicated"
  | "resume_settings_updated"
  | "resume_tailored"
  | "resume_checked"
  | "resume_status_changed"
  | "resume_approved"
  | "resume_approval_revoked"
  | "resume_archived"
  | "resume_unarchived"
  | "resume_exported"
  | "resume_export_failed"
  | "ai_preferences_updated"
  | "private_cloud_ai_enabled"
  | "private_cloud_ai_disabled"
  | "ai_provider_tested"
  | "communication_created"
  | "communication_edited"
  | "communication_version_created"
  | "communication_restored"
  | "communication_checked"
  | "communication_status_changed"
  | "communication_approved"
  | "communication_approval_revoked"
  | "communication_archived"
  | "communication_unarchived"
  | "communication_exported"
  | "communication_export_failed"
  | "communication_generated"
  | "communication_generation_failed"
  | "communication_imported"
  | "communication_duplicated"
  | "recipient_context_saved"
  | "recipient_context_deleted"
  | "communication_preferences_saved"
  | "communication_package_created"
  | "communication_package_updated"
  | "communication_package_checked"
  | "communication_package_ready"
  | "communication_package_stale"
  | "communication_package_invalid"
  | "communication_package_archived"
  | "communication_package_handoff"
  | "application_created"
  | "application_status_changed"
  | "application_policy_changed"
  | "application_attempt_started"
  | "application_submission_started"
  | "application_submitted"
  | "application_submission_uncertain"
  | "application_submission_failed"
  | "application_user_confirmed"
  | "application_channel_discovered"
  | "application_form_discovered"
  | "application_field_mapped"
  | "application_answer_generated"
  | "application_answer_edited"
  | "application_answer_approved"
  | "application_approved"
  | "application_approval_invalidated"
  | "application_autofill_started"
  | "application_autofill_completed"
  | "application_paused"
  | "application_resumed"
  | "application_stopped"
  | "workflow_created"
  | "workflow_edited"
  | "workflow_version_saved"
  | "workflow_activated"
  | "workflow_deactivated"
  | "workflow_archived"
  | "workflow_restored"
  | "workflow_duplicated"
  | "workflow_exported"
  | "workflow_imported"
  | "signature_preset_saved"
  | "signature_preset_deleted";

export interface AuditEntry {
  userId: string;
  action: AuditAction;
  resourceType: string;
  resourceId?: string | null;
  metadata?: Record<string, string | number | boolean | null | string[]>;
  actorType?: "USER" | "SYSTEM";
  requestId?: string | null;
}

export async function recordAudit(tx: Tx, entry: AuditEntry): Promise<void> {
  await tx.auditLog.create({
    data: {
      userId: entry.userId,
      actorType: entry.actorType ?? "USER",
      actorId: entry.actorType === "SYSTEM" ? null : entry.userId,
      action: entry.action,
      resourceType: entry.resourceType,
      resourceId: entry.resourceId ?? null,
      metadata: entry.metadata ?? {},
      requestId: entry.requestId ?? null,
    },
  });
}
