import "server-only";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { getServerEnv } from "@/config/env";
import { AppError } from "./errors";

/**
 * Object storage for candidate documents.
 *  - Production/staging: Supabase Storage, private bucket, server-side service role only.
 *  - Development without Supabase: local directory (never used when APP_ENV != development).
 * Keys are generated by the server: <userId>/<candidateId>/<documentId>/original
 * — never derived from user-supplied file names.
 */
export interface ObjectStorage {
  readonly kind: "supabase" | "local" | "memory";
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array>;
  remove(keys: string[]): Promise<void>;
  /** Short-lived URL, or null when the app must stream the bytes itself. */
  signedDownloadUrl(
    key: string,
    downloadName: string,
    expiresInSeconds: number,
  ): Promise<string | null>;
}

export function documentStorageKey(
  userId: string,
  candidateId: string,
  documentId: string,
): string {
  return `${userId}/${candidateId}/${documentId}/original`;
}

function storageError(message: string, cause?: unknown): AppError {
  return new AppError("EXTERNAL_SERVICE_ERROR", {
    message,
    cause,
    publicMessage: "File storage is unavailable. Please try again.",
    retryable: true,
  });
}

class SupabaseObjectStorage implements ObjectStorage {
  readonly kind = "supabase" as const;
  constructor(
    private readonly client: SupabaseClient,
    private readonly bucket: string,
  ) {}

  async put(key: string, bytes: Uint8Array, contentType: string) {
    const { error } = await this.client.storage
      .from(this.bucket)
      .upload(key, bytes, { contentType, upsert: false });
    if (error) throw storageError(`Supabase upload failed: ${error.message}`, error);
  }

  async get(key: string) {
    const { data, error } = await this.client.storage.from(this.bucket).download(key);
    if (error || !data) throw storageError(`Supabase download failed: ${error?.message}`, error);
    return new Uint8Array(await data.arrayBuffer());
  }

  async remove(keys: string[]) {
    if (keys.length === 0) return;
    const { error } = await this.client.storage.from(this.bucket).remove(keys);
    if (error) throw storageError(`Supabase remove failed: ${error.message}`, error);
  }

  async signedDownloadUrl(key: string, downloadName: string, expiresInSeconds: number) {
    const { data, error } = await this.client.storage
      .from(this.bucket)
      .createSignedUrl(key, expiresInSeconds, { download: downloadName });
    if (error || !data) throw storageError(`Supabase signed URL failed: ${error?.message}`, error);
    return data.signedUrl;
  }
}

class LocalObjectStorage implements ObjectStorage {
  readonly kind = "local" as const;
  constructor(private readonly root: string) {}

  private resolve(key: string) {
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root))) throw storageError("Invalid storage key");
    return full;
  }

  async put(key: string, bytes: Uint8Array) {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, bytes, { flag: "wx" });
  }

  async get(key: string) {
    try {
      return new Uint8Array(await readFile(this.resolve(key)));
    } catch (error) {
      throw storageError("Local file missing", error);
    }
  }

  async remove(keys: string[]) {
    await Promise.all(keys.map((key) => rm(this.resolve(key), { force: true })));
  }

  async signedDownloadUrl() {
    return null;
  }
}

/** In-memory storage for tests. */
export class MemoryObjectStorage implements ObjectStorage {
  readonly kind = "memory" as const;
  readonly files = new Map<string, Uint8Array>();
  async put(key: string, bytes: Uint8Array) {
    if (this.files.has(key)) throw storageError("Object exists");
    this.files.set(key, bytes);
  }
  async get(key: string) {
    const file = this.files.get(key);
    if (!file) throw storageError("Object missing");
    return file;
  }
  async remove(keys: string[]) {
    keys.forEach((key) => this.files.delete(key));
  }
  async signedDownloadUrl() {
    return null;
  }
}

const globalForStorage = globalThis as unknown as { jobhuntStorage?: ObjectStorage };

export function getSupabaseAdmin(): SupabaseClient | null {
  const env = getServerEnv();
  if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY) return null;
  return createClient(env.SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

export function getStorage(): ObjectStorage {
  if (globalForStorage.jobhuntStorage) return globalForStorage.jobhuntStorage;
  const env = getServerEnv();
  const supabase = getSupabaseAdmin();
  if (supabase) {
    globalForStorage.jobhuntStorage = new SupabaseObjectStorage(
      supabase,
      env.SUPABASE_STORAGE_BUCKET,
    );
  } else if (env.APP_ENV === "development") {
    globalForStorage.jobhuntStorage = new LocalObjectStorage(path.resolve(env.LOCAL_STORAGE_DIR));
  } else {
    throw new AppError("EXTERNAL_SERVICE_ERROR", {
      message: "Supabase Storage is not configured",
      publicMessage: "File storage is not configured.",
    });
  }
  return globalForStorage.jobhuntStorage;
}

export function setStorageForTests(storage: ObjectStorage | undefined): void {
  globalForStorage.jobhuntStorage = storage;
}
