-- CreateTable
CREATE TABLE "companies" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "name_normalized" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "companies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jobs" (
    "id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "source_id" UUID,
    "source_key" TEXT NOT NULL,
    "source_type" TEXT NOT NULL,
    "source_status" TEXT NOT NULL,
    "external_job_id" TEXT,
    "title" TEXT NOT NULL,
    "normalized_title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "location_raw" TEXT NOT NULL,
    "city" TEXT,
    "region" TEXT,
    "country_code" CHAR(2),
    "employment_type" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "employment_type_raw" TEXT,
    "remote_status" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "remote_status_raw" TEXT,
    "relocation_available" TEXT NOT NULL DEFAULT 'UNKNOWN',
    "salary_min" INTEGER,
    "salary_max" INTEGER,
    "salary_currency" CHAR(3),
    "salary_period" TEXT,
    "salary_raw" TEXT,
    "posted_at" DATE,
    "discovered_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_seen_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "job_url" TEXT NOT NULL,
    "application_url" TEXT,
    "source_url" TEXT,
    "visa_text_raw" TEXT,
    "notes" TEXT,
    "content_hash" CHAR(64) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "visibility" TEXT NOT NULL,
    "created_by_user_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "jobs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "companies_name_normalized_key" ON "companies"("name_normalized");

-- CreateIndex
CREATE INDEX "jobs_created_by_user_id_deleted_at_created_at_idx" ON "jobs"("created_by_user_id", "deleted_at", "created_at" DESC);

-- CreateIndex
CREATE INDEX "jobs_visibility_status_idx" ON "jobs"("visibility", "status");

-- CreateIndex
CREATE INDEX "jobs_company_id_idx" ON "jobs"("company_id");

-- CreateIndex
CREATE INDEX "jobs_source_id_idx" ON "jobs"("source_id");

-- CreateIndex
CREATE INDEX "jobs_country_code_idx" ON "jobs"("country_code");

-- AddForeignKey
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_company_id_fkey" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "job_sources"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_country_code_fkey" FOREIGN KEY ("country_code") REFERENCES "countries"("code") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ===========================================================================
-- Hand-written section (not generated by Prisma)
-- ===========================================================================

-- --- Integrity constraints ---------------------------------------------------
ALTER TABLE "companies" ADD CONSTRAINT "companies_name_len_ck" CHECK (char_length("name") BETWEEN 1 AND 200 AND char_length("name_normalized") >= 1);

ALTER TABLE "jobs" ADD CONSTRAINT "jobs_source_key_ck"     CHECK ("source_key" IN ('MANUAL', 'ASHBY', 'LEVER', 'GREENHOUSE'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_source_type_ck"    CHECK ("source_type" IN ('MANUAL', 'ATS_PUBLIC_API'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_source_status_ck"  CHECK ("source_status" IN ('USER_ENTERED', 'DISCOVERED'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_status_ck"         CHECK ("status" IN ('OPEN', 'CLOSED', 'STALE', 'UNKNOWN'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_visibility_ck"     CHECK ("visibility" IN ('PUBLIC', 'PRIVATE'));
-- A private job must have an owner; manual jobs are always private and user-entered.
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_private_owner_ck"  CHECK ("visibility" <> 'PRIVATE' OR "created_by_user_id" IS NOT NULL);
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_manual_ck"         CHECK ("source_key" <> 'MANUAL' OR ("source_type" = 'MANUAL' AND "source_status" = 'USER_ENTERED' AND "visibility" = 'PRIVATE'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_employment_ck"     CHECK ("employment_type" IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', 'APPRENTICESHIP', 'FREELANCE', 'UNKNOWN'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_remote_ck"         CHECK ("remote_status" IN ('REMOTE', 'HYBRID', 'ONSITE', 'UNKNOWN'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_relocation_ck"     CHECK ("relocation_available" IN ('YES', 'NO', 'UNKNOWN'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_salary_period_ck"  CHECK ("salary_period" IS NULL OR "salary_period" IN ('YEAR', 'MONTH', 'WEEK', 'HOUR', 'UNKNOWN'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_salary_range_ck"   CHECK (("salary_min" IS NULL OR "salary_min" >= 0) AND ("salary_max" IS NULL OR "salary_max" >= 0) AND ("salary_min" IS NULL OR "salary_max" IS NULL OR "salary_min" <= "salary_max"));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_salary_currency_ck" CHECK ("salary_currency" IS NULL OR "salary_currency" ~ '^[A-Z]{3}$');
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_urls_ck"           CHECK ("job_url" ~ '^https?://' AND ("application_url" IS NULL OR "application_url" ~ '^https?://') AND ("source_url" IS NULL OR "source_url" ~ '^https?://'));
ALTER TABLE "jobs" ADD CONSTRAINT "jobs_lengths_ck"        CHECK (
  char_length("title") BETWEEN 1 AND 300
  AND char_length("description") BETWEEN 1 AND 50000
  AND char_length("location_raw") BETWEEN 1 AND 200
  AND char_length("job_url") <= 2048
  AND ("application_url" IS NULL OR char_length("application_url") <= 2048)
  AND ("visa_text_raw" IS NULL OR char_length("visa_text_raw") <= 2000)
  AND ("notes" IS NULL OR char_length("notes") <= 5000)
);

-- Basic identity for discovered jobs (full deduplication comes later).
CREATE UNIQUE INDEX "jobs_source_external_id_uq" ON "jobs" ("source_id", "external_job_id") WHERE "external_job_id" IS NOT NULL;

-- --- Row Level Security -------------------------------------------------------
ALTER TABLE "companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;

-- Companies: shared catalog. The app may read and add; never rename or delete.
GRANT SELECT, INSERT ON "companies" TO jobhunt_app;
CREATE POLICY "companies_read" ON "companies" FOR SELECT TO jobhunt_app USING (true);
CREATE POLICY "companies_insert" ON "companies" FOR INSERT TO jobhunt_app WITH CHECK (true);

-- Jobs: public (shared, not deleted) or the caller's own private jobs.
GRANT SELECT, INSERT, UPDATE ON "jobs" TO jobhunt_app;
CREATE POLICY "jobs_select" ON "jobs" FOR SELECT TO jobhunt_app
  USING (("visibility" = 'PUBLIC' AND "deleted_at" IS NULL) OR "created_by_user_id" = (SELECT app_current_user_id()));
-- The app can only create PRIVATE jobs owned by the caller (shared jobs are written by the system).
CREATE POLICY "jobs_insert_own_private" ON "jobs" FOR INSERT TO jobhunt_app
  WITH CHECK ("visibility" = 'PRIVATE' AND "created_by_user_id" = (SELECT app_current_user_id()));
CREATE POLICY "jobs_update_own_private" ON "jobs" FOR UPDATE TO jobhunt_app
  USING ("visibility" = 'PRIVATE' AND "created_by_user_id" = (SELECT app_current_user_id()))
  WITH CHECK ("visibility" = 'PRIVATE' AND "created_by_user_id" = (SELECT app_current_user_id()));
-- No DELETE grant: jobs are soft-deleted (deleted_at) and purged by maintenance after 30 days.

DO $$
DECLARE
  r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON "companies", "jobs" FROM %I', r);
    END IF;
  END LOOP;
END
$$;
