-- CreateTable
CREATE TABLE "job_sources" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "source_key" TEXT NOT NULL,
    "source_name" TEXT NOT NULL,
    "source_type" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "access_method" TEXT NOT NULL,
    "terms_status" TEXT NOT NULL,
    "terms_reviewed_at" TIMESTAMPTZ(3),
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "configuration" JSONB NOT NULL DEFAULT '{}',
    "rate_limit_settings" JSONB NOT NULL DEFAULT '{}',
    "notes" TEXT,
    "last_tested_at" TIMESTAMPTZ(3),
    "last_sync_at" TIMESTAMPTZ(3),
    "last_success_at" TIMESTAMPTZ(3),
    "last_error" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "job_sources_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "job_sources_user_id_source_key_key" ON "job_sources"("user_id", "source_key");

-- AddForeignKey
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ===========================================================================
-- Hand-written section (not generated by Prisma)
-- ===========================================================================

-- Closed value sets (internal product states — never an external legal approval).
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_source_key_ck"    CHECK ("source_key" IN ('ASHBY', 'LEVER', 'GREENHOUSE', 'MANUAL'));
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_source_type_ck"   CHECK ("source_type" IN ('ATS_PUBLIC_API', 'MANUAL'));
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_status_ck"        CHECK ("status" IN ('PENDING_VERIFICATION', 'READY', 'MANUAL_ONLY', 'ERROR'));
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_access_method_ck" CHECK ("access_method" IN ('PUBLIC_POSTINGS_API', 'USER_ENTERED'));
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_terms_status_ck"  CHECK ("terms_status" IN ('NOT_REVIEWED', 'VERIFIED', 'RESTRICTED', 'NOT_APPLICABLE'));
-- A source can only claim VERIFIED terms with a recorded review date.
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_terms_review_ck"  CHECK ("terms_status" <> 'VERIFIED' OR "terms_reviewed_at" IS NOT NULL);
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_config_object_ck" CHECK (jsonb_typeof("configuration") = 'object' AND jsonb_typeof("rate_limit_settings") = 'object');
ALTER TABLE "job_sources" ADD CONSTRAINT "job_sources_notes_len_ck"     CHECK ("notes" IS NULL OR char_length("notes") <= 1000);

-- --- Row Level Security -------------------------------------------------------

-- Harden the context function: fixed search_path (Supabase linter: function_search_path_mutable).
ALTER FUNCTION app_current_user_id() SET search_path = '';

ALTER TABLE "job_sources" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON "job_sources" TO jobhunt_app;
-- (select …) makes Postgres evaluate the function once per statement instead of per row.
CREATE POLICY "job_sources_owner" ON "job_sources" FOR ALL TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()))
  WITH CHECK ("user_id" = (SELECT app_current_user_id()));

-- Retrofit Phase 1 policies with the same per-statement evaluation (behaviour unchanged).
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'candidate_profiles', 'candidate_education', 'candidate_experiences', 'candidate_projects',
    'candidate_achievements', 'candidate_skills', 'candidate_certifications', 'candidate_portfolio_items',
    'candidate_languages', 'candidate_work_authorizations', 'candidate_preferences',
    'candidate_target_locations', 'candidate_documents', 'candidate_fact_candidates', 'ai_generations'
  ]
  LOOP
    EXECUTE format(
      'ALTER POLICY %I ON %I USING ("user_id" = (SELECT app_current_user_id())) WITH CHECK ("user_id" = (SELECT app_current_user_id()))',
      t || '_owner', t
    );
  END LOOP;
END
$$;
ALTER POLICY "users_self_select" ON "users" USING ("id" = (SELECT app_current_user_id()));
ALTER POLICY "audit_logs_owner_select" ON "audit_logs" USING ("user_id" = (SELECT app_current_user_id()));
ALTER POLICY "audit_logs_owner_insert" ON "audit_logs" WITH CHECK ("user_id" = (SELECT app_current_user_id()));

-- Supabase Data API roles: no access to the new table.
DO $$
DECLARE
  r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON "job_sources" FROM %I', r);
    END IF;
  END LOOP;
END
$$;
