-- Supabase advisor fixes (security + performance). No data changes.


-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_profiles_current_country_code_idx" ON "candidate_profiles"("current_country_code");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_education_source_document_id_idx" ON "candidate_education"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_experiences_source_document_id_idx" ON "candidate_experiences"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_projects_source_document_id_idx" ON "candidate_projects"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_achievements_experience_id_idx" ON "candidate_achievements"("experience_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_achievements_project_id_idx" ON "candidate_achievements"("project_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_achievements_source_document_id_idx" ON "candidate_achievements"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_skills_source_document_id_idx" ON "candidate_skills"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_certifications_source_document_id_idx" ON "candidate_certifications"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_portfolio_items_project_id_idx" ON "candidate_portfolio_items"("project_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_portfolio_items_source_document_id_idx" ON "candidate_portfolio_items"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_languages_source_document_id_idx" ON "candidate_languages"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_work_authorizations_country_code_idx" ON "candidate_work_authorizations"("country_code");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_work_authorizations_source_document_id_idx" ON "candidate_work_authorizations"("source_document_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_target_locations_country_code_idx" ON "candidate_target_locations"("country_code");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "candidate_fact_candidates_ai_generation_id_idx" ON "candidate_fact_candidates"("ai_generation_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_matches_ai_generation_id_idx" ON "job_matches"("ai_generation_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_matches_requirement_set_id_idx" ON "job_matches"("requirement_set_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_runs_ai_generation_id_idx" ON "research_runs"("ai_generation_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_runs_company_id_idx" ON "research_runs"("company_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_runs_job_id_idx" ON "research_runs"("job_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_sources_company_id_idx" ON "research_sources"("company_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_sources_job_id_idx" ON "research_sources"("job_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "company_research_company_id_idx" ON "company_research"("company_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "company_research_run_id_idx" ON "company_research"("run_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_research_company_id_idx" ON "job_research"("company_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_research_company_research_id_idx" ON "job_research"("company_research_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_research_job_id_idx" ON "job_research"("job_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_research_requirement_set_id_idx" ON "job_research"("requirement_set_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "job_research_run_id_idx" ON "job_research"("run_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_notes_company_id_idx" ON "research_notes"("company_id");

-- CreateIndex (unindexed_foreign_keys)
CREATE INDEX "research_notes_job_id_idx" ON "research_notes"("job_id");

-- ===========================================================================
-- Hand-written section (not generated by Prisma)
-- ===========================================================================

-- [security] function_search_path_mutable: pin the trigger function's search_path.
-- It only reads NEW/OLD, so an empty search_path is safe.
ALTER FUNCTION public.resume_versions_protect_approved() SET search_path = '';

-- [performance] multiple_permissive_policies: the FOR ALL "own/write" policies also applied to
-- SELECT, so every read evaluated two permissive policies. Each "read"/"select" policy already
-- covers the caller's own rows, so the write policies are split into INSERT/UPDATE/DELETE with
-- the SAME expressions. Access is unchanged; reads now evaluate one policy.

-- market_locations
DROP POLICY "market_locations_own" ON "market_locations";
CREATE POLICY "market_locations_insert_own" ON "market_locations" FOR INSERT TO jobhunt_app
  WITH CHECK ("user_id" = (SELECT app_current_user_id()));
CREATE POLICY "market_locations_update_own" ON "market_locations" FOR UPDATE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id())) WITH CHECK ("user_id" = (SELECT app_current_user_id()));
CREATE POLICY "market_locations_delete_own" ON "market_locations" FOR DELETE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()));

-- job_categories
DROP POLICY "job_categories_own" ON "job_categories";
CREATE POLICY "job_categories_insert_own" ON "job_categories" FOR INSERT TO jobhunt_app
  WITH CHECK ("user_id" = (SELECT app_current_user_id()));
CREATE POLICY "job_categories_update_own" ON "job_categories" FOR UPDATE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id())) WITH CHECK ("user_id" = (SELECT app_current_user_id()));
CREATE POLICY "job_categories_delete_own" ON "job_categories" FOR DELETE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()));

-- job_category_terms
DROP POLICY "job_category_terms_own" ON "job_category_terms";
CREATE POLICY "job_category_terms_insert_own" ON "job_category_terms" FOR INSERT TO jobhunt_app
  WITH CHECK ("user_id" = (SELECT app_current_user_id()) AND EXISTS (SELECT 1 FROM "job_categories" c WHERE c."id" = "category_id"));
CREATE POLICY "job_category_terms_update_own" ON "job_category_terms" FOR UPDATE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()))
  WITH CHECK ("user_id" = (SELECT app_current_user_id()) AND EXISTS (SELECT 1 FROM "job_categories" c WHERE c."id" = "category_id"));
CREATE POLICY "job_category_terms_delete_own" ON "job_category_terms" FOR DELETE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()));

-- job_category_assignments
DROP POLICY "job_category_assignments_own" ON "job_category_assignments";
CREATE POLICY "job_category_assignments_insert_own" ON "job_category_assignments" FOR INSERT TO jobhunt_app
  WITH CHECK ("user_id" = (SELECT app_current_user_id())
    AND EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id")
    AND EXISTS (SELECT 1 FROM "job_categories" c WHERE c."id" = "category_id"));
CREATE POLICY "job_category_assignments_update_own" ON "job_category_assignments" FOR UPDATE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()))
  WITH CHECK ("user_id" = (SELECT app_current_user_id())
    AND EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id")
    AND EXISTS (SELECT 1 FROM "job_categories" c WHERE c."id" = "category_id"));
CREATE POLICY "job_category_assignments_delete_own" ON "job_category_assignments" FOR DELETE TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()));

-- job_requirement_sets (no DELETE grant: sets are versioned, never deleted by the app)
DROP POLICY "job_requirement_sets_write_own" ON "job_requirement_sets";
CREATE POLICY "job_requirement_sets_insert_own" ON "job_requirement_sets" FOR INSERT TO jobhunt_app
  WITH CHECK (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())));
CREATE POLICY "job_requirement_sets_update_own" ON "job_requirement_sets" FOR UPDATE TO jobhunt_app
  USING (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())))
  WITH CHECK (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())));

-- job_requirements
DROP POLICY "job_requirements_write_own" ON "job_requirements";
CREATE POLICY "job_requirements_insert_own" ON "job_requirements" FOR INSERT TO jobhunt_app
  WITH CHECK (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())));
CREATE POLICY "job_requirements_update_own" ON "job_requirements" FOR UPDATE TO jobhunt_app
  USING (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())))
  WITH CHECK (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())));
CREATE POLICY "job_requirements_delete_own" ON "job_requirements" FOR DELETE TO jobhunt_app
  USING (EXISTS (SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE' AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())));
