-- CreateTable
CREATE TABLE "job_requirements" (
    "id" UUID NOT NULL,
    "job_id" UUID NOT NULL,
    "category" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "normalized_value" JSONB NOT NULL DEFAULT '{}',
    "required_level" TEXT NOT NULL,
    "source_text" TEXT NOT NULL,
    "confidence" DOUBLE PRECISION NOT NULL,
    "source_reference" TEXT NOT NULL,
    "extraction_method" TEXT NOT NULL,
    "extractor_version" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "job_requirements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_matches" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "job_id" UUID NOT NULL,
    "candidate_id" UUID NOT NULL,
    "overall_status" TEXT NOT NULL,
    "summary_score" INTEGER,
    "hard_block" BOOLEAN NOT NULL DEFAULT false,
    "hard_block_reason" TEXT,
    "explanation" JSONB NOT NULL DEFAULT '{}',
    "matching_version" TEXT NOT NULL,
    "freshness" TEXT NOT NULL DEFAULT 'CURRENT',
    "candidate_snapshot_hash" CHAR(64) NOT NULL,
    "job_content_hash" CHAR(64) NOT NULL,
    "computed_at" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "job_matches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "job_match_dimensions" (
    "id" UUID NOT NULL,
    "match_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "dimension" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "is_hard" BOOLEAN NOT NULL DEFAULT false,
    "summary" TEXT NOT NULL,
    "evidence" JSONB NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "job_match_dimensions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "job_requirements_job_id_category_idx" ON "job_requirements"("job_id", "category");

-- CreateIndex
CREATE INDEX "job_matches_user_id_overall_status_idx" ON "job_matches"("user_id", "overall_status");

-- CreateIndex
CREATE INDEX "job_matches_job_id_idx" ON "job_matches"("job_id");

-- CreateIndex
CREATE INDEX "job_matches_candidate_id_idx" ON "job_matches"("candidate_id");

-- CreateIndex
CREATE UNIQUE INDEX "job_matches_user_id_job_id_key" ON "job_matches"("user_id", "job_id");

-- CreateIndex
CREATE INDEX "job_match_dimensions_user_id_idx" ON "job_match_dimensions"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "job_match_dimensions_match_id_dimension_key" ON "job_match_dimensions"("match_id", "dimension");

-- AddForeignKey
ALTER TABLE "job_requirements" ADD CONSTRAINT "job_requirements_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_candidate_id_fkey" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_match_dimensions" ADD CONSTRAINT "job_match_dimensions_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "job_matches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "job_match_dimensions" ADD CONSTRAINT "job_match_dimensions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ===========================================================================
-- Hand-written section (not generated by Prisma)
-- ===========================================================================

-- --- Closed value sets & integrity ----------------------------------------------
ALTER TABLE "job_requirements" ADD CONSTRAINT "job_requirements_category_ck" CHECK ("category" IN (
  'REQUIRED_SKILL', 'PREFERRED_SKILL', 'REQUIRED_EXPERIENCE', 'PREFERRED_EXPERIENCE',
  'REQUIRED_EDUCATION', 'PREFERRED_EDUCATION', 'REQUIRED_LANGUAGE', 'PREFERRED_LANGUAGE',
  'WORK_AUTHORIZATION', 'LOCATION', 'WORK_MODE', 'EMPLOYMENT_TYPE', 'SALARY', 'CERTIFICATION', 'OTHER'
));
ALTER TABLE "job_requirements" ADD CONSTRAINT "job_requirements_level_ck"      CHECK ("required_level" IN ('REQUIRED', 'PREFERRED', 'UNSPECIFIED'));
ALTER TABLE "job_requirements" ADD CONSTRAINT "job_requirements_method_ck"     CHECK ("extraction_method" IN ('RULE', 'AI', 'USER'));
ALTER TABLE "job_requirements" ADD CONSTRAINT "job_requirements_confidence_ck" CHECK ("confidence" >= 0 AND "confidence" <= 1);
-- Traceability: every requirement keeps its original wording and where it came from.
ALTER TABLE "job_requirements" ADD CONSTRAINT "job_requirements_trace_ck"      CHECK (
  char_length("text") BETWEEN 1 AND 500
  AND char_length("source_text") BETWEEN 1 AND 2000
  AND char_length("source_reference") BETWEEN 1 AND 200
  AND jsonb_typeof("normalized_value") = 'object'
);

ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_overall_ck"   CHECK ("overall_status" IN ('STRONG_MATCH', 'GOOD_MATCH', 'PARTIAL_MATCH', 'REVIEW', 'BLOCKED'));
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_freshness_ck" CHECK ("freshness" IN ('CURRENT', 'STALE', 'REQUIRES_RECALCULATION'));
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_score_ck"     CHECK ("summary_score" IS NULL OR "summary_score" BETWEEN 0 AND 100);
-- A hard block must say why, and BLOCKED is used exactly when there is a hard block.
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_block_ck"     CHECK (("hard_block" = ("overall_status" = 'BLOCKED')) AND ("hard_block" = false OR char_length(coalesce("hard_block_reason", '')) > 0));
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_explanation_ck" CHECK (jsonb_typeof("explanation") = 'object' AND char_length("matching_version") BETWEEN 1 AND 20);

ALTER TABLE "job_match_dimensions" ADD CONSTRAINT "job_match_dimensions_dimension_ck" CHECK ("dimension" IN (
  'SKILLS', 'EXPERIENCE', 'EDUCATION', 'PROJECTS', 'PORTFOLIO', 'LOCATION', 'WORK_MODE',
  'EMPLOYMENT_TYPE', 'SALARY', 'WORK_AUTHORIZATION', 'LANGUAGE', 'CAREER_PREFERENCES'
));
ALTER TABLE "job_match_dimensions" ADD CONSTRAINT "job_match_dimensions_status_ck" CHECK ("status" IN (
  'STRONG_MATCH', 'MATCH', 'PARTIAL_MATCH', 'UNKNOWN', 'GAP', 'BLOCKED', 'NOT_APPLICABLE'
));
ALTER TABLE "job_match_dimensions" ADD CONSTRAINT "job_match_dimensions_evidence_ck" CHECK (jsonb_typeof("evidence") = 'array' AND char_length("summary") BETWEEN 1 AND 1000);

-- --- Row Level Security -------------------------------------------------------
ALTER TABLE "job_requirements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_matches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_match_dimensions" ENABLE ROW LEVEL SECURITY;

-- Requirements follow their job: readable when the job is visible to the caller;
-- writable only for the caller's own, non-deleted private jobs.
GRANT SELECT, INSERT, UPDATE, DELETE ON "job_requirements" TO jobhunt_app;
CREATE POLICY "job_requirements_select" ON "job_requirements" FOR SELECT TO jobhunt_app
  USING (EXISTS (
    SELECT 1 FROM "jobs" j WHERE j."id" = "job_id"
      AND ((j."visibility" = 'PUBLIC' AND j."deleted_at" IS NULL) OR j."created_by_user_id" = (SELECT app_current_user_id()))
  ));
CREATE POLICY "job_requirements_write_own" ON "job_requirements" FOR ALL TO jobhunt_app
  USING (EXISTS (
    SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE'
      AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM "jobs" j WHERE j."id" = "job_id" AND j."visibility" = 'PRIVATE'
      AND j."deleted_at" IS NULL AND j."created_by_user_id" = (SELECT app_current_user_id())
  ));

-- Matches: owner only; a match may only reference the caller's own candidate
-- profile and a job the caller can see.
GRANT SELECT, INSERT, UPDATE, DELETE ON "job_matches" TO jobhunt_app;
CREATE POLICY "job_matches_owner" ON "job_matches" FOR ALL TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()))
  WITH CHECK (
    "user_id" = (SELECT app_current_user_id())
    AND EXISTS (SELECT 1 FROM "candidate_profiles" c WHERE c."id" = "candidate_id" AND c."user_id" = (SELECT app_current_user_id()))
    AND EXISTS (
      SELECT 1 FROM "jobs" j WHERE j."id" = "job_id"
        AND ((j."visibility" = 'PUBLIC' AND j."deleted_at" IS NULL) OR j."created_by_user_id" = (SELECT app_current_user_id()))
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON "job_match_dimensions" TO jobhunt_app;
CREATE POLICY "job_match_dimensions_owner" ON "job_match_dimensions" FOR ALL TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()))
  WITH CHECK (
    "user_id" = (SELECT app_current_user_id())
    AND EXISTS (SELECT 1 FROM "job_matches" m WHERE m."id" = "match_id" AND m."user_id" = (SELECT app_current_user_id()))
  );

DO $$
DECLARE
  r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON "job_requirements", "job_matches", "job_match_dimensions" FROM %I', r);
    END IF;
  END LOOP;
END
$$;
