-- AlterTable
ALTER TABLE "ai_generations" ADD COLUMN     "attempt" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "output_hash" CHAR(64),
ADD COLUMN     "prompt_key" TEXT,
ADD COLUMN     "route_reason" TEXT,
ADD COLUMN     "sensitivity" TEXT;

-- CreateTable
CREATE TABLE "ai_preferences" (
    "user_id" UUID NOT NULL,
    "primary_provider" TEXT NOT NULL DEFAULT 'auto',
    "gemini_for_public" BOOLEAN NOT NULL DEFAULT true,
    "allow_private_cloud" BOOLEAN NOT NULL DEFAULT false,
    "private_cloud_consented_at" TIMESTAMPTZ(3),
    "auto_fallback" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "ai_preferences_pkey" PRIMARY KEY ("user_id")
);

-- AddForeignKey
ALTER TABLE "ai_preferences" ADD CONSTRAINT "ai_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ===========================================================================
-- Hand-written section (not generated by Prisma)
-- ===========================================================================

ALTER TABLE "ai_generations" ADD CONSTRAINT "ai_generations_orchestration_ck" CHECK (
  ("sensitivity" IS NULL OR "sensitivity" IN ('PUBLIC', 'INTERNAL', 'PRIVATE_CANDIDATE', 'HIGH_SENSITIVITY'))
  AND "attempt" BETWEEN 1 AND 10
  AND ("output_hash" IS NULL OR "output_hash" ~ '^[0-9a-f]{64}$')
  AND ("route_reason" IS NULL OR char_length("route_reason") <= 300)
);
-- Per-user cache lookups for PUBLIC tasks (same task + prompt + input).
CREATE INDEX "ai_generations_cache_idx" ON "ai_generations" ("user_id", "task", "input_hash", "created_at" DESC);

ALTER TABLE "ai_preferences" ADD CONSTRAINT "ai_preferences_ck" CHECK (
  "primary_provider" IN ('auto', 'ollama', 'gemini')
  -- Consent to private cloud processing is always explicit and timestamped.
  AND ("allow_private_cloud" = false OR "private_cloud_consented_at" IS NOT NULL)
);

-- Row Level Security: owner only.
ALTER TABLE "ai_preferences" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON "ai_preferences" TO jobhunt_app;
CREATE POLICY "ai_preferences_owner" ON "ai_preferences" FOR ALL TO jobhunt_app
  USING ("user_id" = (SELECT app_current_user_id()))
  WITH CHECK ("user_id" = (SELECT app_current_user_id()));

DO $$
DECLARE
  r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON "ai_preferences" FROM %I', r);
    END IF;
  END LOOP;
END
$$;
